"""
Classifier-based evaluation of synthetic peripheral blood cell images.

This module evaluates whether a classifier trained on real images
correctly recognizes synthetic samples generated by diffusion models.

Reported metrics include:
- Accuracy
- Balanced accuracy
- Macro F1-score
- Per-class accuracy
- Confusion matrix
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List, Optional

import numpy as np
import torch
import torch.nn as nn

from PIL import Image

from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    confusion_matrix,
    f1_score,
)

from torch.utils.data import (
    DataLoader,
    Dataset,
)

from torchvision import (
    models,
    transforms,
)

from tqdm import tqdm


# DATASET

class SyntheticDataset(Dataset):
    """
    Load synthetic images from:
    synthetic_dir/{class_name}/*.png
    """

    def __init__(
        self,
        synthetic_dir: Path,
        class_to_idx,
        transform=None,
    ):

        self.synthetic_dir = Path(synthetic_dir)

        self.transform = transform

        self.class_to_idx = class_to_idx

        self.samples = []

        for class_name, class_idx in class_to_idx.items():

            class_dir = (
                self.synthetic_dir /
                class_name.lower()
            )

            if not class_dir.exists():
                continue

            for extension in (
                "*.png",
                "*.jpg",
                "*.jpeg",
            ):

                for image_path in class_dir.glob(extension):

                    self.samples.append(
                        (
                            image_path,
                            class_idx,
                            class_name,
                        )
                    )

    def __len__(self) -> int:

        return len(self.samples)

    def __getitem__(self, idx: int):

        image_path, label, class_name = (
            self.samples[idx]
        )

        image = (
            Image.open(image_path)
            .convert("RGB")
        )

        if self.transform:
            image = self.transform(image)

        return image, label, class_name


# LOAD CLASSIFIER

def load_classifier(
    checkpoint_path: Path,
    device: str = "cpu",
):

    checkpoint = torch.load(
        checkpoint_path,
        map_location=device,
    )

    classes = [

        "basophil",
        "eosinophil",
        "erythroblast",
        "ig",
        "lymphocyte",
        "monocyte",
        "neutrophil",
        "platelet",
    ]

    class_to_idx = {

        class_name: idx

        for idx, class_name
        in enumerate(classes)
    }

    model = models.efficientnet_b0(
        weights=None
    )

    model.classifier[1] = nn.Linear(
        model.classifier[1].in_features,
        len(classes),
    )

    model.load_state_dict(
        checkpoint["model_state_dict"]
    )

    model = model.to(device).eval()

    return (
        model,
        classes,
        class_to_idx,
    )


# EVALUATION

def evaluate_synthetic(
    model: nn.Module,
    synthetic_dir: Path,
    class_to_idx: Dict[str, int],
    classes: List[str],
    device: str = "cuda",
    batch_size: int = 32,
    num_workers: int = 4,
) -> Optional[Dict]:

    transform = transforms.Compose([

        transforms.Resize((224, 224)),

        transforms.ToTensor(),

        transforms.Normalize(

            mean=[0.485, 0.456, 0.406],

            std=[0.229, 0.224, 0.225],
        ),
    ])

    dataset = SyntheticDataset(
        synthetic_dir,
        class_to_idx,
        transform,
    )

    if len(dataset) == 0:
        return None

    dataloader = DataLoader(

        dataset,

        batch_size=batch_size,

        shuffle=False,

        num_workers=num_workers,

        pin_memory=(device == "cuda"),
    )

    all_predictions = []

    all_labels = []

    all_probabilities = []

    with torch.no_grad():

        for images, labels, _ in tqdm(
            dataloader,
            desc=f"Evaluating {synthetic_dir.name}",
        ):

            images = images.to(device)

            outputs = model(images)

            probabilities = torch.softmax(
                outputs,
                dim=1,
            )

            predictions = outputs.argmax(dim=1)

            all_predictions.extend(
                predictions.cpu().numpy()
            )

            all_labels.extend(
                labels.numpy()
            )

            all_probabilities.extend(
                probabilities.cpu().numpy()
            )

    all_predictions = np.array(all_predictions)

    all_labels = np.array(all_labels)

    all_probabilities = np.array(all_probabilities)

    results = {

        "n_samples": len(all_labels),

        "accuracy": float(
            accuracy_score(
                all_labels,
                all_predictions,
            )
        ),

        "balanced_accuracy": float(
            balanced_accuracy_score(
                all_labels,
                all_predictions,
            )
        ),

        "f1_macro": float(
            f1_score(
                all_labels,
                all_predictions,
                average="macro",
                zero_division=0,
            )
        ),

        "f1_weighted": float(
            f1_score(
                all_labels,
                all_predictions,
                average="weighted",
                zero_division=0,
            )
        ),
    }

    per_class = {}

    for idx, class_name in enumerate(classes):

        mask = all_labels == idx

        if mask.sum() == 0:
            continue

        correct = int(
            (
                all_predictions[mask]
                == idx
            ).sum()
        )

        total = int(mask.sum())

        per_class[class_name] = {

            "n_samples": total,

            "correct": correct,

            "accuracy": float(
                correct / total
            ),

            "mean_confidence": float(
                all_probabilities[mask, idx]
                .mean()
            ),
        }

    results["per_class"] = per_class

    results["confusion_matrix"] = (
        confusion_matrix(
            all_labels,
            all_predictions,
        ).tolist()
    )

    return results


# CLI

def main(argv=None) -> None:

    parser = argparse.ArgumentParser(

        description=(
            "Evaluate synthetic images "
            "using a trained classifier."
        )
    )

    parser.add_argument(
        "--classifier_path",
        type=str,
        required=True,
    )

    parser.add_argument(
        "--synthetic_dirs",
        type=str,
        nargs="+",
        required=True,
    )

    parser.add_argument(
        "--names",
        type=str,
        nargs="+",
        required=True,
    )

    parser.add_argument(
        "--output",
        type=str,
        default="outputs/oracle_evaluation.json",
    )

    parser.add_argument(
        "--device",
        type=str,
        default="cpu",
    )

    parser.add_argument(
        "--batch_size",
        type=int,
        default=32,
    )

    args = parser.parse_args(argv)

    if len(args.synthetic_dirs) != len(args.names):

        raise ValueError(
            "--synthetic_dirs and --names "
            "must have the same length."
        )

    model, classes, class_to_idx = load_classifier(

        Path(args.classifier_path),

        args.device,
    )

    results = {
        "models": {}
    }

    for synthetic_dir, name in zip(
        args.synthetic_dirs,
        args.names,
    ):

        evaluation = evaluate_synthetic(

            model=model,

            synthetic_dir=Path(synthetic_dir),

            class_to_idx=class_to_idx,

            classes=classes,

            device=args.device,

            batch_size=args.batch_size,
        )

        if evaluation is None:
            continue

        results["models"][name] = {

            "directory": synthetic_dir,

            **evaluation,
        }

        print(
            f"{name}: "
            f"F1={evaluation['f1_macro']:.4f}"
        )

    output_path = Path(args.output)

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    with open(output_path, "w") as file:

        json.dump(
            results,
            file,
            indent=2,
        )

    print(
        f"Results saved to: {output_path}"
    )


if __name__ == "__main__":
    main()